language: node_js
node_js:
- "10.9"
install:
  - npm install
script:
  - npm run cypress:ci
branches:
  - master
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_ApiKey
  app: delgadotrueba-angular-login
  on:
    branch: master